#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '
🏗️ 👷 👷‍♀️ QA Walking your code now
---------------------------------
'

if ! git diff --no-ext-diff --quiet --exit-code; then
  echo 'You have unstaged changes do you wish to proceed? This is going to check all of your files not just staged changes'
  select yn in "Yes" "No"; do
    case $yn in
      Yes ) git add .; break;;
      No ) break;;
    esac
  done < /dev/tty
fi


# Check Prettier standards
npm run check-format ||
(
echo '
🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
Prettier Check Failed. Run npm run format, add changes and try commit again.
';

false;
)


# Check ESLint Standards
npm run lint ||
(
echo '
😤🏀👋😤 Do you want to be a remediation pro?😤🏀👋😤 
ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.
'

false; 
)


# Check tsconfig standards
npm run check-types ||
(
echo '
🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
Are you seriously trying to write that? Make the changes required above.
'

false;
)


# If everything passes... Now we can commit
echo '
🤔🤔🤔🤔... Alright Alright Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔
'

npm run build ||
(
echo '
❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
Next build failed: View the errors above to see why. 
'

false;
)


# If everything passes... Now we can commit
echo '
✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'